version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  app:
    build: .
    # While we can just run a development server, its more convenient to do this from inside the container
    # This means we can restart the server, chnage gems, etc, without rebuilding
    # To run from inside container:
    # First run: docker exec -it `docker ps -aqf "name=auction_app_1"` /bin/bash
    #command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    command: bash -c "mkdir -p log; touch log/development.log ; tail -f log/development.log"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db_data: {}
