name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13.3.0
      uses: actions/setup-node@v1
      with:
        node-version: 13.3.0
    - run: | 
        npm install
        npm install -g yarn
    - uses: actions/checkout@master
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        NODE_ENV=test bundle exec rails webpacker:compile
        RAILS_ENV=test bundle exec rake
      env:
        RAILS_ENV: test
        NODE_ENV: test  
    container:
      image: ruby:2.6.5
